[workspace]
authors = ["fecet <xiezej@gmail.com>"]
channels = ["https://repo.prefix.dev/meta-forge", "conda-forge"]
name = "quarto-arxiv"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
quarto = "*"
r-tidyverse = "*"
r-kableextra = "*"
